version: "3"
services:
  redis:
    image: "redis"
    ports:
      - 6379:6379

  rabbitmq:
    image: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
      - 15671:15671
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq
  draw-guess:
    build: .
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
